import type { PageSchema } from './types';

export const schema: PageSchema = {
  route: '전체 투자실적',
  title: '전체 투자실적',
  kind: 'list',
  entity: '투자실적',
  columns: [
    { key: 'no',            label: 'No',          type: 'number', align: 'center' },
    { key: 'year',          label: '연도',        type: 'text',   align: 'center' },
    { key: 'sector',        label: '분야',        type: 'text',   align: 'center' },
    { key: 'fundName',      label: '펀드명',      type: 'text',   align: 'left' },
    { key: 'registeredAt',  label: '등록일자',    type: 'date',   align: 'center' },
    { key: 'fundAmount',    label: '결성액',      type: 'amount', unit: '원', align: 'right' },
    { key: 'investee',      label: '투자업체',    type: 'text',   align: 'left' },
    { key: 'bizSector',     label: '사업분야',    type: 'text',   align: 'left' },
    { key: 'bizContent',    label: '사업내용',    type: 'text',   align: 'left' },
    { key: 'investMethod',  label: '투자방식',    type: 'text',   align: 'center' },
    { key: 'investDate',    label: '투심일자',    type: 'date',   align: 'center' },
    { key: 'firstInvestDate', label: '최초 투자일자', type: 'date', align: 'center' },
    { key: 'investSeqNo',   label: '투자건 No',  type: 'number', align: 'center' },
    { key: 'investAmt',     label: '투자금액',    type: 'amount', unit: '원', align: 'right' },
    { key: 'investPeriod',  label: '투자기간',    type: 'text',   align: 'center' },
    { key: 'recoverAmt',    label: '회수실적',    type: 'amount', unit: '원', align: 'right' },
    { key: 'investBalance', label: '투자잔액',    type: 'amount', unit: '원', align: 'right' },
    { key: 'isFullRecovered', label: '회수완료 여부', type: 'status', align: 'center' },
    { key: 'isAgri',        label: '농식품 여부', type: 'status', align: 'center' },
    { key: 'isVenture',     label: '벤처투자 여부', type: 'status', align: 'center' },
    { key: 'isMandatory',   label: '의무투자 여부', type: 'status', align: 'center' },
  ],
  fields: [],
  filters: ['계정구분', '데이터기준', '기준일자'],
  searchable: true,
  hideCardView: true,
  provenance: {
    capturedAt: '2026-09-12',
    sourceSystem: 'FFMS',
    captureFile: '/Users/younghwankang/Downloads/통합/01_투자자산관리/S1_33_전체_투자실적.html',
  },
};
