import type { PageSchema } from './types';

export const schema: PageSchema = {
  route: '투심승인정보조회',
  title: '투심승인정보조회',
  kind: 'list',
  entity: '투심승인정보',
  columns: [
    { key: 'no',           label: 'No',         type: 'number', align: 'center' },
    { key: 'gp',           label: '운용사',     type: 'gp',     align: 'left' },
    { key: 'subFund',      label: '자펀드',     type: 'text',   align: 'left' },
    { key: 'investee',     label: '투자기업',   type: 'text',   align: 'left' },
    { key: 'paymentDue',   label: '투자금 납입 예정일', type: 'date', align: 'center' },
    // 라벨에 단위를 박으면 헤더가 `투자금액(원) (원)` 이 된다 — 단위는 unit 이 소유한다
    { key: 'investAmt',    label: '투자금액', type: 'amount', unit: '원', align: 'right' },
    { key: 'ceobirthDate', label: '대표이사 생년월일', type: 'pii', align: 'center' },
    { key: 'isVenture',    label: '벤처인증여부', type: 'status', align: 'center' },
    { key: 'isWoman',      label: '여성기업여부', type: 'status', align: 'center' },
    { key: 'isYouth',      label: '청년기업여부', type: 'status', align: 'center' },
    { key: 'establishDate', label: '설립일자',  type: 'date', align: 'center' },
    { key: 'bizNo',        label: '사업자번호/주민번호', type: 'pii', align: 'center' },
    { key: 'mandatory',    label: '의무투자',   type: 'status', align: 'center' },
    { key: 'smallScale',   label: '일정규모 이하투자', type: 'status', align: 'center' },
    { key: 'agriInvest',   label: '농업투자여부', type: 'status', align: 'center' },
    { key: 'bizSector',    label: '사업분야',   type: 'text',   align: 'left' },
    { key: 'investMethod', label: '투자방식',   type: 'text',   align: 'center' },
    { key: 'investPeriod', label: '투자기간',   type: 'text',   align: 'center' },
    { key: 'location',     label: '소재지',     type: 'text',   align: 'left' },
  ],
  fields: [],
  filters: ['운용사', '자펀드', '계정구분', '기준일자'],
  searchable: true,
  hideCardView: true,
  hideKpis: true,
  provenance: {
    capturedAt: '2026-09-12',
    sourceSystem: 'FFMS',
    captureFile: '/Users/younghwankang/Downloads/통합/01_투자자산관리/S1_28_투심승인정보조회.html',
  },
};
